add non-ascii filename support
maxcountryman/flask-uploads pull request #11
Opened 2017-02-04 04:42 UTC by greyli

Make sure the file's extension will be returned. Werkzeug's `secure_filename()` function will return empty when the filename is non-ASCII string.

2018-10-18 13:56 UTC, maxcountryman requested changes
Seems like we could also add a test for this. What do you think?

2018-10-18 14:20 UTC, greyli commented
Sure, I will do it.

2018-10-18 15:15 UTC, greyli commented
@maxcountryman Test added.

2020-02-09 16:20 UTC, maxcountryman commented
Thanks!

2020-02-09 16:20 UTC, merged